export const ROOM_AMENITIES_OPTIONS = ['Extra Towels', 'Feather Free', 'Refrigerator'];

export const COMMUNICATION_OPTIONS = ['Email', 'SMS/Text Message', 'Postal Mail'];

export const DIETARY_OPTIONS = [
  'Gluten Free',
  'Kosher/Halal',
  'Low Fat',
  'Low Sodium',
  'Low Sugar',
  'No Alcohol',
  'No Beef',
  'No Dairy',
  'No Eggs',
  'No Fish',
  'No Nuts',
  'No Peanuts',
  'No Pork',
  'No Shellfish',
  'No Soy',
  'No Wheat',
  'Vegan',
  'Vegetarian',
];

export const FOOD_OPTIONS = [
  'Appetizers',
  'Breakfast Foods',
  'Candy',
  'Chocolate',
  'Fruit',
  'Granola/Health Bars',
  'Noodle Dishes',
  'Pasta',
  'Pizza',
  'Rice Dishes',
  'Sandwiches',
  'Snacks - Frozen',
  'Snacks - Salty',
  'Snacks - Sweet',
  'Yogurt',
];

export const BEVERAGE_OPTIONS = [
  'Coffee - Decaf',
  'Coffee - Regular',
  'Coffee - Specialty',
  'Energy Drink',
  'Juice',
  'Milk',
  'Milk - Non-Dairy',
  'Smoothie',
  'Soda - Diet',
  'Soda - Ginger Ale',
  'Soda - Other',
  'Soda - Regular',
  'Tea',
  'Tea - Decaf',
  'Water - Regular',
  'Water - Sparkling',
];

export const ALCOHOL_OPTIONS = [
  'Beer',
  'Bourbon',
  'Cognac/Brandy',
  'Gin',
  'Non-Alcoholic - Beer',
  'Non-Alcoholic - Mocktail',
  'Rum',
  'Scotch Whiskey',
  'Tequila',
  'Vodka',
  'Whiskey',
  'Wine - Red',
  'Wine - Rose',
  'Wine - Sparkling',
  'Wine - White',
];

export const COUNTRIES = ['USA', 'Canada', 'United Kingdom', 'France', 'Japan', 'Germany', 'Italy'];

export const STATES = [
  'Tennessee',
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
];

export const COUNTRY_CODES = ['+1', '+44', '+33', '+81', '+49', '+39'];

export const MONTHS = [
  { value: '01', label: 'January' },
  { value: '02', label: 'February' },
  { value: '03', label: 'March' },
  { value: '04', label: 'April' },
  { value: '05', label: 'May' },
  { value: '06', label: 'June' },
  { value: '07', label: 'July' },
  { value: '08', label: 'August' },
  { value: '09', label: 'September' },
  { value: '10', label: 'October' },
  { value: '11', label: 'November' },
  { value: '12', label: 'December' },
];

export const FLOOR_OPTIONS = ['High Floor', 'Low Floor', 'Near Elevator', 'No Preference'];
export const PILLOW_OPTIONS = [
  'Foam Pillows',
  'Extra Foam Pillows',
  'Extra Feather Pillows',
  'No Preference',
];
