#!/bin/sh
# commit-msg.sh <msg-file>
# Warns on style issues; blocks only when LEFTHOOK_STRICT=1.

MSG_FILE="$1"
MSG=$(cat "$MSG_FILE")
ISSUES=0

report() {
  if [ "$ISSUES" -eq 0 ]; then
    printf '\n'
    printf 'commit-msg: heads up. Not blocking. Set LEFTHOOK_STRICT=1 to enforce.\n'
    printf '\n'
  fi
  ISSUES=$((ISSUES + 1))
  printf '  %s\n\n' "$1"
}

# 1. Em dashes (strong AI tell)
EM_DASH=$(printf '\xe2\x80\x94')
if printf '%s' "$MSG" | grep -q "$EM_DASH"; then
  report "Em dash found in message.
    Em dashes are a strong AI tell. Use commas, parens, or hyphens instead.
    bad:  Add login flow -- handles MFA
    good: Add login flow with MFA handling"
fi

# 2. AI mentions
if printf '%s' "$MSG" | grep -qiE 'claude|copilot|cursor[- ]ai|generated by|with assistance from|written by AI|AI[- ](gener|assist)'; then
  report "AI mention found in message.
    Commits stay attributable to a single human author for this project.
    Remove references to AI tools, 'generated by', etc."
fi

# 3. Co-Authored-By footer
if printf '%s' "$MSG" | grep -qiE '^co-authored-by:'; then
  report "Co-Authored-By footer found.
    Drop the footer. Keep commits attributable to one human author."
fi

# 4. Subject length
SUBJECT=$(head -1 "$MSG_FILE")
LEN=${#SUBJECT}
if [ "$LEN" -gt 72 ]; then
  report "Subject line is $LEN chars, target is 72 or less.
    Shorten or move detail to the body, leaving one blank line after subject.
    bad:  feat: Add comprehensive user authentication with OAuth2 and MFA support
    good: feat: Add OAuth2 authentication with MFA"
fi

# 5. Emojis in subject
if printf '%s' "$SUBJECT" | LC_ALL=C grep -qP '[\x{1F300}-\x{1FAFF}\x{2600}-\x{27BF}]' 2>/dev/null; then
  report "Emoji found in subject line.
    No emojis in commit messages. Stick to plain text.
    bad:  feat: Add login flow
    good: feat: Add login flow"
fi

if [ "$ISSUES" -gt 0 ]; then
  printf 'commit-msg: %d issue(s) found.\n' "$ISSUES"
  if [ "$LEFTHOOK_STRICT" = "1" ]; then
    printf 'LEFTHOOK_STRICT=1 is set, blocking this commit. Unset to merge with warnings.\n' >&2
    exit 1
  fi
  printf 'Tip: amend with git commit --amend if you want to fix this now.\n'
fi

exit 0
